# Generated by Django 5.0.3 on 2024-03-11 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={"ordering": ("-published",)},
        ),
    ]
