# Generated by Django 5.0.3 on 2024-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_posts_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
    ]
