# Generated by Django 5.0.3 on 2024-03-15 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_posts_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="images",
        ),
    ]
